name: Ekaya Vision
favicon: null
layout_spectrum: 0.48602
typography_spectrum: 0.24563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#031428'
    - '#6d747e'
    - '#354052'
    - '#09d555'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
